parameters:
    rabbit_connector.writer.file.rabbitmq_product.class: Balance\Bundle\RabbitMQBundle\Writer\File\RabbitMQProductWriter
services:
    rabbit_connector.writer.file.rabbitmq_product:
        class: %rabbit_connector.writer.file.rabbitmq_product.class%
        arguments:
            - '@pim_connector.writer.file.file_path_resolver'
            - '@akeneo_buffer.factory.json_file_buffer'
            - '@pim_connector.writer.file.file_exporter'